### ISSUE TITLE
Iobroker integration? 

### ISSUE THREAD

**Issue by itProfi** [dzavalishin/mqtt_udp#136]
Would be wonderful! :) http://www.iobroker.net

**Comment by dzavalishin** [comment]
It has MQTT broker mode, so we already have integration. 

http://www.iobroker.net/docu/?page_id=6435&lang=en

And Lang/python3/examples/mqtt_bidir_gate.py is the answer. :)

If they have their own API, please let me know, i’ll take a look

**Comment by itProfi** [comment]
Можно по-русски? :) Т.е. это уже готовый шлюз, я так понимаю?

**Comment by dzavalishin** [comment]
Конечно можно. :)
Да, там шлюз в обычный mqtt с защитой от петель. И есть ещё шлюз в openHAB, но я им не вполне доволен.

**Comment by dzavalishin** [comment]
Чуть подробнее:

В lang/python3/examples лежат сам щлюз (mqtt_bidir_gate.py ) и пример файла конфигурации mqtt-udp.ini, в нём:

```
[mqtt-gate]
host = http://whatever
port=8080

#login = 
#password = 

subscribe=#
```

Я проверял его на другом облачном сервисе, ну и, конечно, на локальном.

Для проверки что всё работает удобно запустить ``tools/viewer/MqttUdpViewer.exe`` (на юниксе ``java -jar MqttUdpViewer.jar``) или, в командной строке, один из:

* ``lang/python3/examples/dump.py``
* ``lang/c/mqtt_udp_listen``
* ``lang/lua/examples/mqtt_sub.lua``

**Comment by itProfi** [comment]
Спасибо большое, будем эксперементировать!
