### ISSUE TITLE
What License does this repo have?

### ISSUE THREAD

**Issue by harryhaaren** [dzavalishin/mqtt_udp#150]
Under what license is your code here released? The C library/example code shows ` * Copyright (C) 2017-2019 Dmitry Zavalishin, dz@dz.ru` (https://github.com/dzavalishin/mqtt_udp/blob/master/lang/c/examples/pub.c#L7), but what is the intent on allowing re-use (if any?)

To simplify, is this code under MIT, GPL, LGPL, BSD, or something else?

To allow packaging etc, adding a LICENSE file to the root of the repo is required. For even better practice consider including SPDX tags in each file?

**Comment by dzavalishin** [comment]
Thanx for pointing. Ity will be MIT license.
