### ISSUE TITLE
Lua implementation note

### ISSUE THREAD

**Issue by xHasKx** [dzavalishin/mqtt_udp#29]
Hello

There is a new pure-Lua implementation of MQTT 3.1.1 protocol here: https://github.com/xHasKx/luamqtt

The MQTT protocol packets parsing/creating may be taken from mqtt/protocol.lua module in that repo.
This module may be used in your MQTT/UDP implementation (almost) without changes because of (almost) zero dependencies.

Sorry, I don't have time resources to PR to your project, but maybe you may find something useful in my project.

Thanks for your attention, and good luck!

**Comment by dzavalishin** [comment]
Thanx!

**Comment by dzavalishin** [comment]
Thank you for `bit` proxy/implementation!
